robots:
  - name: RM1
    beacon: 1
    serial: 159CKC50070ECX
    init_orientation: 90.0

  - name: RM2
    beacon: 2
    serial: 159CKC50070E5N
    init_orientation: 90.0

  - name: RM3
    beacon: 3
    serial: 159CG9J0050797
    init_orientation: 90.0

  - name: RM4
    beacon: 4
    serial: 159CG9V0050HED
    init_orientation: 90.0
